FROM python:3.12
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY app/ app/
COPY scripts/ scripts/
COPY model/ model/
ENV PYTHONPATH=/app
CMD ["python", "-m", "app.streaming.consumer.consumer"]
